name: Cron actions

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - name: Repo checkout
          uses: "actions/checkout@v2"

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"